In [1]:
lat = sage.crypto.gen_lattice(n=2, m=3, q=6, seed=42)
print(lat)

[ 6  0  0]
[ 0  6  0]
[-1  1  1]


In [14]:
from sage.modules.free_module_integer import IntegerLattice
Base = sage.crypto.gen_lattice(type='modular', n=1, m=3, seed=5)
L = IntegerLattice(Base)
print(L)
print(L.shortest_vector())

Free module of degree 3 and rank 3 over Integer Ring
User basis matrix:
[ 1  0  1]
[ 1 -2 -2]
[-2 -1  2]
(1, 0, 1)


In [15]:
matrix_space = sage.matrix.matrix_space.MatrixSpace(ZZ, 3)
Rand = sage.matrix.special.random_unimodular_matrix(matrix_space, upper_bound=5)
print(Rand)

[-1  1  0]
[-2  1  3]
[ 2 -1 -2]


In [16]:
L_bad = Base*Rand
print(L_bad)
L_bad_lat = IntegerLattice(L_bad)
L_bad_short_vect = L_bad_lat.shortest_vector()
print(L_bad_short_vect)

[-11  11   0]
[ -6   5   3]
[  1   0  -2]
(-2, 1, 0)


In [17]:
Red = L_bad_lat.reduced_basis
print('Reduced')
print(Red)
L_good = L_bad_lat.LLL()
print('Reduced with LLL')
print(L_good)
print(L_good==Red)
L_good_short_vect = IntegerLattice(L_good).shortest_vector()
print('Shortest vector', L_good_short_vect)

Reduced
[-2  1  0]
[ 1  0 -2]
[ 1  2  1]
Reduced with LLL
[-2  1  0]
[ 1  0 -2]
[ 1  2  1]
True
Shortest vector (1, 0, -2)


In [19]:
import pickle
import numpy
#from sage.misc.persist import SagePickler
outputdir = '/home/adam/Desktop/work/2021 Summer Research/code' 
if L_bad_short_vect.norm() != L_good_short_vect.norm():
    print('Somethings wrong!')
else:
    L_short_vect = L_good_short_vect
bases = [L_bad.numpy(), L_good.numpy(), L_short_vect]
with open(outputdir+'/bases', 'wb') as f:
            pickle.dump(bases,f)